"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Activity, ArrowRight, Check, Code2, GitBranch, LockKeyhole, Package, Play, RefreshCw, Send, Terminal, TriangleAlert, Webhook, Zap } from "lucide-react";

const icons = { Activity, Code2, GitBranch, LockKeyhole, Package, RefreshCw, Send, Terminal, TriangleAlert, Webhook, Zap };

export function DeveloperPage({ eyebrow, title, description, label, code, capabilities, steps, detailTitle, details = [] }) {
  return (
    <main className="bg-white text-[#101828]">
      <section className="relative overflow-hidden bg-[#07111f] text-white">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(1,142,222,.24),transparent_28%),radial-gradient(circle_at_12%_85%,rgba(0,168,255,.12),transparent_30%)]" />
        <div className="relative mx-auto grid max-w-[1480px] items-center gap-14 px-6 py-20 sm:px-10 sm:py-28 lg:grid-cols-[.9fr_1.1fr] lg:px-16 lg:py-32">
          <motion.div initial={{ opacity: 0, x: -24 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .65 }}>
            <p className="text-xs font-extrabold uppercase tracking-[.3em] text-sky-300">{eyebrow}</p>
            <h1 className="mt-6 max-w-2xl text-5xl font-black leading-[1.02] tracking-[-.045em] sm:text-6xl lg:text-7xl">{title}</h1>
            <p className="mt-7 max-w-xl text-lg leading-8 text-white/70">{description}</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="/signup" className="inline-flex items-center gap-2 rounded-full bg-[#018EDE] px-6 py-4 text-sm font-bold text-white transition hover:bg-sky-500">Start building <ArrowRight className="h-4 w-4" /></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-6 py-4 text-sm font-bold text-white transition hover:bg-white/10">Talk to an expert</Link></div>
          </motion.div>
          <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, delay: .1 }} className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#0c1929] p-3 shadow-2xl shadow-black/40"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex gap-2"><span className="h-3 w-3 rounded-full bg-red-400" /><span className="h-3 w-3 rounded-full bg-yellow-400" /><span className="h-3 w-3 rounded-full bg-green-400" /></div><span className="text-xs font-bold text-white/30">{label}</span><Terminal className="h-4 w-4 text-white/30" /></div><div className="p-6 font-mono text-sm leading-7 text-[#d4e7e9] sm:p-8"><p><span className="text-green-400">POST</span> <span className="text-white/70">/v1/payments</span></p><p className="mt-5 text-white/45">&#123;</p>{code.map(([key, value]) => <p key={key} className="pl-5"><span className="text-sky-300">&quot;{key}&quot;</span><span className="text-white/50">: </span><span className="text-green-200">&quot;{value}&quot;</span>,</p>)}<p className="text-white/45">&#125;</p><div className="mt-6 flex items-center gap-2 rounded-xl border border-green-400/10 bg-green-400/5 px-4 py-3 font-sans text-xs font-bold text-green-300"><Check className="h-4 w-4" /> Response 200 · ready for production</div></div></motion.div>
        </div>
      </section>

     

      <section className="py-24 lg:py-32"><div className="mx-auto max-w-[1480px] px-6 sm:px-10 lg:px-16"><div className="max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[.3em] text-[#078f9a]">Built for your workflow</p><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Tools that help your team ship with confidence.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{capabilities.map(([icon, heading, text], index) => { const Icon = icons[icon] || Code2; return <motion.article key={heading} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} className="group border-t-2 border-[#078f9a] bg-white p-8 shadow-[0_14px_35px_rgba(16,47,59,.06)] transition hover:-translate-y-1"><span className="grid h-12 w-12 place-items-center bg-[#e4f1f1] text-[#078f9a] transition group-hover:bg-[#078f9a] group-hover:text-white"><Icon className="h-5 w-5" /></span><h3 className="mt-8 text-xl font-bold">{heading}</h3><p className="mt-3 leading-7 text-[#668087]">{text}</p></motion.article>; })}</div></div></section>

      {details.length > 0 && <section className="bg-[#f6f8fa] py-24 lg:py-28"><div className="mx-auto max-w-[1480px] px-6 sm:px-10 lg:px-16"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.3em] text-[#018EDE]">Developer resources</p><h2 className="mt-5 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">{detailTitle}</h2></div><span className="font-mono text-xs text-[#667085]">finunique.dev / resources</span></div><div className="mt-14 grid gap-5 md:grid-cols-2">{details.map(([icon, heading, text, meta], index) => { const Icon = icons[icon] || Code2; return <motion.article key={heading} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} className="group flex gap-5 rounded-2xl border border-[#d9e7eb] bg-white p-6 shadow-[0_12px_30px_rgba(16,47,59,.05)] transition hover:-translate-y-1 hover:border-[#018EDE]/40"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#eaf7ff] text-[#018EDE]"><Icon className="h-5 w-5" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h3 className="text-lg font-bold">{heading}</h3><span className="rounded-full bg-[#f0f8fc] px-2.5 py-1 font-mono text-[10px] font-bold text-[#018EDE]">{meta}</span></div><p className="mt-2 leading-7 text-[#667085]">{text}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#018EDE]">Explore resource <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></motion.article>; })}</div></div></section>}

      <section className="bg-[#eaf4f4] py-24" id="implementation"><div className="mx-auto max-w-[1480px] px-6 sm:px-10 lg:px-16"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-extrabold uppercase tracking-[.3em] text-[#078f9a]">Implementation path</p><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">From first request to live traffic.</h2></div><div className="grid gap-0 md:grid-cols-3">{steps.map(([number, heading, text]) => <article key={number} className="border-l border-[#9bc9cb] px-6 py-6 first:border-l-0 first:pl-0"><span className="text-4xl font-black text-[#078f9a]/50">{number}</span><h3 className="mt-7 text-xl font-bold">{heading}</h3><p className="mt-3 leading-7 text-[#668087]">{text}</p></article>)}</div></div></div></section>

      <section className="bg-[#102f3b] py-20 text-white"><div className="mx-auto flex max-w-[1480px] flex-col justify-between gap-8 px-6 sm:px-10 md:flex-row md:items-center lg:px-16"><div><p className="text-xs font-extrabold uppercase tracking-[.3em] text-[#78e3dc]">Build with Finunique</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-tight sm:text-5xl">Your next integration starts here.</h2></div><Link href="/contact" className="inline-flex w-fit items-center gap-2 rounded-md bg-[#78e3dc] px-7 py-4 text-sm font-bold text-[#102f3b] transition hover:bg-white">Get started <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main>
  );
}
