import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BarChart3, Check, Code2, CreditCard, Globe2, LockKeyhole, MessageSquare, Send, ShieldCheck, Smartphone, Sparkles, WalletCards } from "lucide-react";

const chartOne = [22,34,29,48,42,57,45,64,70,54,76,82];
const chartTwo = [30,44,38,52,46,60,66,58,72,76,69,84];

function MiniChart({ values, color }) {
  return <div className="flex h-14 items-end gap-1">{values.map((height,index)=><span key={index} className={`flex-1 rounded-t-sm ${color}`} style={{height:`${height}%`}}/>)}</div>;
}

export function FuturisticHero() {
  return (
    <section className="relative isolate overflow-hidden bg-gradient-to-br from-white via-[#f5fbfe] to-cloud pb-6 pt-6 text-ink sm:pt-8">
      <div className="absolute left-[42%] top-20 h-[520px] w-[520px] rounded-full bg-cyan-300/20 blur-[110px]"/>
      <div className="absolute -right-28 bottom-20 h-96 w-96 rounded-full bg-sky-300/20 blur-[100px]"/>
      <div className="absolute inset-0 opacity-40 [background-image:radial-gradient(rgba(7,143,209,.12)_1px,transparent_1px)] [background-size:24px_24px] [mask-image:linear-gradient(to_bottom,black,transparent_80%)]"/>

      <div className="page-shell relative">
        <div className="grid min-h-[460px] items-center gap-6 lg:grid-cols-[.7fr_1.3fr]">
          <div className="relative z-20 py-6">
            <div className="inline-flex animate-hero-copy items-center gap-2 rounded-full border border-sky-200 bg-white/80 px-4 py-2 text-xs font-bold text-ocean shadow-sm backdrop-blur"><Sparkles className="h-4 w-4"/>All-in-one payments platform</div>
            <h1 className="mt-5 max-w-[520px] animate-hero-copy text-[2.35rem] font-black leading-[1.1] tracking-[-.04em] [animation-delay:100ms] sm:text-[2.8rem] xl:text-[3.15rem]">Powering business payments. <span className="mt-2 block animate-gradient-shift bg-gradient-to-r from-ocean via-cyan-500 to-sky-500 bg-[length:200%_200%] bg-clip-text text-[.76em] leading-[1.08] text-transparent">Anytime. Anywhere.</span></h1>
            <p className="mt-4 max-w-md animate-hero-copy text-sm leading-6 text-slate-600 [animation-delay:200ms] sm:text-[15px] sm:leading-7">Accept payments, automate payouts, verify businesses and manage financial operations—all through one secure platform designed to scale with your business.</p>
            <div className="mt-7 flex animate-hero-copy flex-wrap gap-3 [animation-delay:300ms]"><Link href="/signup" className="group inline-flex items-center gap-2.5 rounded-xl bg-gradient-to-r from-ocean to-cyan-500 px-5 py-3 text-[13px] font-bold text-white shadow-[0_10px_26px_rgba(7,143,209,.22)] transition-all hover:-translate-y-0.5 hover:shadow-[0_14px_32px_rgba(7,143,209,.3)]">Get started <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></Link><Link href="/contact" className="inline-flex items-center gap-2.5 rounded-xl border border-slate-200 bg-white/85 px-5 py-3 text-[13px] font-bold text-ink shadow-sm transition hover:-translate-y-0.5 hover:border-sky-200 hover:bg-white">Talk to sales <MessageSquare className="h-4 w-4"/></Link></div>
            <div className="mt-8 flex animate-hero-copy items-center gap-4 [animation-delay:400ms]"><p className="max-w-[120px] text-[9px] font-extrabold uppercase leading-4 tracking-[.13em] text-slate-400">Trusted by 1 lakh+ businesses</p><div className="h-8 w-px shrink-0 bg-slate-200"/><div className="flex items-center gap-2">{[CreditCard,Send,ShieldCheck,WalletCards].map((Icon,index)=><span key={index} className={`grid h-8 w-8 place-items-center rounded-full border border-white shadow-sm ${["bg-sky-50 text-ocean","bg-cyan-50 text-cyan-600","bg-emerald-50 text-emerald-600","bg-amber-50 text-amber-600"][index]}`}><Icon className="h-3.5 w-3.5"/></span>)}</div></div>
          </div>

          <div className="relative min-h-[450px] lg:mr-0 [&>div]:hidden">
            <Image src="/images/hero-parts/ring.png" alt="" width={1536} height={1024} className="absolute -bottom-[8%] left-0 z-0 h-auto w-full -hue-rotate-30 saturate-[.8] object-contain opacity-75 motion-safe:animate-[soft-float_8s_ease-in-out_infinite]"/>
            <Image src="/images/hero-parts/dashboard.png" alt="Finunique analytics dashboard" width={1536} height={1024} priority className="absolute right-0 top-0 z-10 h-auto w-[92%] object-contain drop-shadow-[0_28px_34px_rgba(7,143,209,.12)] motion-safe:animate-dashboard-float"/>
            <Image src="/images/hero-parts/phone.png" alt="Finunique mobile payment application" width={1536} height={1024} className="absolute bottom-0 left-[8%] z-20 h-auto w-[35%] object-contain drop-shadow-[0_24px_28px_rgba(7,143,209,.14)] motion-safe:animate-phone-float"/>
            <Image src="/images/hero-parts/card.png" alt="Finunique contactless business card" width={1536} height={1024} className="absolute bottom-0 right-[3%] z-30 h-auto w-[34%] -hue-rotate-30 saturate-[.82] object-contain drop-shadow-[0_22px_28px_rgba(7,143,209,.18)] motion-safe:animate-card-float"/>
            <Image src="/images/hero-parts/shield.png" alt="Secure by design" width={1536} height={1024} className="absolute right-[1%] top-[2%] z-30 h-auto w-[17%] -hue-rotate-30 saturate-[.82] object-contain drop-shadow-[0_16px_20px_rgba(7,143,209,.18)] motion-safe:animate-float"/>
            <div className="absolute inset-x-[4%] bottom-8 h-44 rounded-[50%] border-[18px] border-violet-300/20 shadow-[0_0_50px_rgba(99,102,241,.16)] [transform:rotate(-7deg)]"/>

            <div className="absolute right-[6%] top-5 w-[76%] rotate-[4deg] rounded-[1.6rem] border border-white bg-white/88 p-4 shadow-[0_28px_65px_rgba(52,61,130,.18)] backdrop-blur-xl motion-safe:animate-dashboard-float sm:p-5">
              <div className="flex items-center gap-3 border-b border-slate-100 pb-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-blue-500 text-white"><BarChart3 className="h-4 w-4"/></span><p className="font-extrabold">Overview</p><span className="ml-auto inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold text-emerald-600"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-500"/>Live</span></div>
              <div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-[9px] font-semibold uppercase tracking-wider text-slate-400">Total volume</p><p className="mt-1.5 text-lg font-black">₹8,75,950</p><MiniChart values={chartOne} color="bg-indigo-400"/></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[9px] font-semibold uppercase tracking-wider text-slate-400">Success rate</p><p className="mt-1.5 text-lg font-black">98.7%</p><MiniChart values={chartTwo} color="bg-emerald-400"/></div></div>
              <div className="mt-3 grid grid-cols-[.7fr_1.3fr] gap-3"><div className="rounded-xl bg-gradient-to-br from-violet-50 to-indigo-50 p-4"><p className="text-[10px] font-bold text-slate-500">Payment methods</p><div className="mx-auto mt-3 grid h-20 w-20 place-items-center rounded-full [background:conic-gradient(#7c3aed_0_42%,#6366f1_42%_68%,#38bdf8_68%_84%,#e2e8f0_84%_100%)]"><div className="grid h-12 w-12 place-items-center rounded-full bg-white text-center text-xs font-black">78%</div></div></div><div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="text-[10px] font-bold text-slate-500">Recent activity</p><span className="text-[9px] font-bold text-indigo-500">View all</span></div><div className="mt-3 space-y-2">{[[CreditCard,"Payment received","+₹25,000","text-emerald-600"],[Send,"Vendor payout","-₹12,500","text-rose-500"],[ShieldCheck,"Bank verified","Complete","text-indigo-600"]].map(([Icon,label,value,color])=><div key={label} className="flex items-center gap-2 rounded-lg bg-white p-2"><span className="grid h-7 w-7 place-items-center rounded-md bg-indigo-50 text-indigo-500"><Icon className="h-3.5 w-3.5"/></span><p className="mr-auto text-[9px] font-bold">{label}</p><span className={`text-[9px] font-extrabold ${color}`}>{value}</span></div>)}</div></div></div>
            </div>

            <div className="absolute bottom-8 left-[3%] z-10 w-[31%] -rotate-[6deg] rounded-[2rem] border-[6px] border-white bg-white p-3 shadow-[0_30px_70px_rgba(52,61,130,.23)] sm:p-4"><div className="flex items-center justify-between"><span className="text-[9px] font-bold">9:31</span><Smartphone className="h-3 w-3"/></div><p className="mt-6 text-[10px] text-slate-400">Total balance</p><p className="mt-1 text-lg font-black sm:text-xl">₹2,45,680</p><div className="mt-4 rounded-xl bg-gradient-to-br from-violet-50 to-blue-50 p-3"><p className="text-[8px] text-slate-400">Today&apos;s collection</p><p className="mt-1 text-xs font-extrabold">₹1,25,430</p></div><div className="mt-4 grid grid-cols-3 gap-2">{[[CreditCard,"Payin"],[Send,"Payout"],[WalletCards,"Split"]].map(([Icon,label])=><div key={label} className="text-center"><span className="mx-auto grid h-8 w-8 place-items-center rounded-lg bg-slate-50 text-indigo-500"><Icon className="h-3.5 w-3.5"/></span><p className="mt-1 text-[7px] font-bold text-slate-500">{label}</p></div>)}</div><div className="mt-4 space-y-2">{["Payment received","Payout complete"].map((label,index)=><div key={label} className="flex items-center gap-2 rounded-lg bg-slate-50 p-2"><span className={`h-2 w-2 rounded-full ${index?"bg-violet-400":"bg-emerald-400"}`}/><p className="text-[7px] font-bold">{label}</p></div>)}</div></div>

            <div className="absolute right-[5%] top-[13%] z-20 animate-float rounded-[1.4rem] bg-gradient-to-br from-violet-500 to-indigo-600 p-4 text-center text-white shadow-[0_18px_40px_rgba(99,102,241,.32)]"><LockKeyhole className="mx-auto h-6 w-6"/><p className="mt-2 text-[9px] font-bold leading-3">Secure<br/>by design</p></div>
            <div className="absolute bottom-1 right-[7%] z-20 w-40 rotate-[8deg] rounded-[1.2rem] bg-gradient-to-br from-violet-400 via-indigo-500 to-blue-500 p-5 text-white shadow-[0_20px_45px_rgba(79,70,229,.3)]"><div className="flex items-center justify-between"><CreditCard className="h-6 w-6"/><span className="text-xl">)))</span></div><p className="mt-8 whitespace-nowrap font-mono text-[10px] tracking-wider text-white/80">1245 5689 4587 9856</p></div>
          </div>
        </div>

        <div className="relative mt-6 overflow-hidden rounded-[1.25rem] border border-sky-100 bg-white shadow-[0_18px_50px_rgba(7,59,76,.12)]"><div className="grid sm:grid-cols-2 lg:grid-cols-4">{[[Globe2,"Connected operations","Built for modern businesses"],[WalletCards,"Multiple methods","Cards, UPI, wallets & more"],[LockKeyhole,"Business security","Protected payment workflows"],[Code2,"Developer friendly","Flexible APIs & integrations"]].map(([Icon,title,text],index)=><div key={title} className={`flex items-center gap-3 p-5 ${index<3?"lg:border-r lg:border-slate-100":""} ${index<2?"border-b border-slate-100 lg:border-b-0":""}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${["bg-sky-50 text-ocean","bg-cyan-50 text-cyan-600","bg-emerald-50 text-emerald-600","bg-amber-50 text-amber-600"][index]}`}><Icon className="h-5 w-5"/></span><div><p className="text-xs font-extrabold text-ink">{title}</p><p className="mt-1 text-[10px] text-slate-500">{text}</p></div></div>)}</div></div>
      </div>
    </section>
  );
}
